### PR TITLE
Request for project approval - Clone of Apple home page.

### PR DESCRIPTION
**Pull request by marcoshdezcam**
- The project uses gradients to mimic the navigation bar on the original site. 
- CSS Flex is used for the layout of the images. 
- Responsive

[Original version](https://web.archive.org/web/20140228164946/http://www.apple.com/)
[Live version](https://marcoshdezcam.github.io/gh-pages-lives/)

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Exceptional job @marcoshdezcam 
This is one of the best projects I've seen :medal_military: Please consider my comments below, make the appropriate changes and request another review :+1: 

#### Descriptive PR
You need a more descriptive PR as it is a hard requirement. Consider describing the work you have completed in the branch in as much detail as you can and even include a link to the live project to speed up your review!
screenshot

#### Horizontal Scroll
You seem to have a little bug with one of the elements of the page, shooting out beyond the browser's maximum width. This may be as a result of a margin or padding you have set up. One of the easiest ways I have found to correct this issue is to set the default `box-sizing` property to `border-box` as follows `*{box-sizing: border-box}`. Please read some more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing).

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by marcoshdezcam** [comment]
Thanks for the comments. Note taken and changes applied.

**Review by rOluochKe — APPROVED** [review]
Hello @marcoshdezcam 

### Congratulations :clap: :boom: your project has passed review 💯 
### You can merge and submit a project completion form from your dashboard

- Happy coding!

**Comment by marcoshdezcam** [comment]
Great! Thanks!

**Pull request merged**
